name = "sql-practice-app-worker"
main = "src/index.js"
compatibility_date = "2023-05-18"

[env.production]
name = "sql-practice-app-worker"

# Environment variables for your Claude API key
[env.production.vars]
ENVIRONMENT = "production"
